import CryptoKit

/// Process-wide receipt key.
///
/// `processKey` is a lazily initialised static, so it is generated by the
/// runtime at first access and is never a compile-time constant baked into the
/// binary. It is held in memory only: never persisted, logged, or exported.
///
/// Consequence, stated so nobody has to infer it: receipts correlate for the
/// lifetime of a daemon process, and are unlinkable across restarts by design.
/// Two daemon instances inside one process share the key and therefore produce
/// matching digests for the same reference; a restart produces a fresh key and
/// receipts that cannot be tied back to the previous process.
enum ReceiptKeyStore {
    static let processKey: SymmetricKey = makeKey()

    /// Fresh random key. Used for the process key and, in tests, to prove the
    /// factory is random rather than fixed.
    static func makeKey() -> SymmetricKey {
        SymmetricKey(size: .bits256)
    }
}
